sudo: false
language: java

env:
    global:
        - THRIFT_PREFIX=$HOME/thrift
        - MAVEN_OPTS=-Dio.netty.leakDetectionLevel=paranoid

cache:
  directories:
    - $HOME/thrift

before_install:
    - export PATH="$PATH:$THRIFT_PREFIX/bin"
    - build/travis/install-thrift.sh
